jQuery.noConflict(),jQuery(document).ready(function(t){function i(){var i=1024,a=768
document.body&&document.body.offsetWidth&&(i=document.body.offsetWidth,a=document.body.offsetHeight),"CSS1Compat"==document.compatMode&&document.documentElement&&document.documentElement.offsetWidth&&(i=document.documentElement.offsetWidth,a=document.documentElement.offsetHeight),window.innerWidth&&window.innerHeight&&(i=window.innerWidth,a=window.innerHeight),t("#mainCanvas").attr({width:i,height:a})}function a(){S=0,w.length=0,I.length=0,n(),t("#objEditorCall").css("background-color",I[S].color),b.fillStyle="rgb(240,240,240)",b.rect(0,0,k,x),b.fill()}function o(t,i,a,o,n){for(this.index=S,this.name=t,this.color=i,this.size=a,this.path=n,this.sound=o,this.firstSound=!1,this.soundPlaying=[0,1],this.interaction=Array(O),B=0;this.interaction.length>B;B++)this.interaction[B]=1
console.log("New creature index:"+this.index)}function n(){var t=Math.floor(45*Math.random()),i=Math.floor(107*Math.random()+100),a=Math.floor(56*Math.random()),n=Math.floor(3*Math.random()+1),e=Math.floor(6*Math.random()+1)
I[I.length]=new o(_[t],"#"+F[a],i,n,e)}function e(t,i){this.type=S,this.index=w.length,this.lifeTime=0,this.x=t,this.y=i,this.pX,this.pY,this.initX=t,this.initY=i,this.trajX=t,this.trajY=i,this.trajpX,this.trajpY,this.trajangle=0,this.trajspeed=.05,this.traj3angle=0,this.traj3section=0,this.traj6section=0,this.traj6angle=0,this.traj8angle=0,this.traj8section=0}function s(){var i='<div id="objEditorCall"></div>'
t("#mainWrapper").append(i),t("#objEditorCall").css("background-color",I[S].color),t("#objEditorCall").fadeIn(1e3),t("#objEditorCall").hover(function(){t("#objEditor").length>0?t("#objEditor").animate({opacity:.5},200):t("#appMenu").length>0?(t("#appMenu").animate({opacity:.5},200),t("#appMenuCall").animate({opacity:.5},200),t("#objEditorCall").animate({opacity:1},200)):t("#objEditorCall").css("border-color","#f8f8f8")},function(){t("#objEditor").length>0?(t("#objEditor").animate({opacity:1},200),t("#objEditorCall").css({opacity:"01","border-color":"#fff"})):t("#appMenu").length>0?(t("#appMenu").animate({opacity:1},200),t("#appMenuCall").animate({opacity:1},200),t("#objEditorCall").animate({opacity:.5},200)):t("#objEditorCall").css("border-color","#fff")}),t("#objEditorCall").click(function(){t("#objEditor").length>0?(t("#objEditor").fadeOut(200,function(){t("#objEditor").remove()}),t("#appMenuCall").animate({opacity:1},200)):t("#appMenu").length>0?(t("#appMenu").fadeOut(200,function(){t("#appMenu").remove(),r(),t("#objEditorCall").css({opacity:"01","border-color":"#fff"})}),t("#appMenuCall").animate({opacity:.5},200)):(r(),t("#objEditorCall").css({opacity:"01","border-color":"#fff"}),t("#appMenuCall").animate({opacity:.5},200))})}function r(){var i='<article id="objEditor"> 				<ul id="objEd-Index"></ul> 				<input id="objEd-Name" type="text" value="Círculo" maxlength="32" /> 				<div id="objEd-Color" class="objEd-Option"> 					<h2>Cor</h2> 				</div> 				<div id="objEd-Size" class="objEd-Option"> 					<h2>Tamanho</h2> 				</div> 				<div id="objEd-Trajectory" class="objEd-Option"> 					<h2>Trajetória</h2> 				</div> 				<div id="objEd-Interaction" class="objEd-Option"> 					<h2>Interação</h2> 				</div> 				<div id="objEd-Sound" class="objEd-Option"> 					<h2>Som</h2> 				</div></article>'
t("#mainWrapper").append(i),l(),t("#objEditor").fadeIn(200)}function h(){var i='<ul id="objEd-Index"></ul> 				<input id="objEd-Name" type="text" value="Círculo" maxlength="32" /> 				<div id="objEd-Color" class="objEd-Option"> 					<h2>Cor</h2> 				</div> 				<div id="objEd-Size" class="objEd-Option"> 					<h2>Tamanho</h2> 				</div> 				<div id="objEd-Trajectory" class="objEd-Option"> 					<h2>Trajetória</h2> 				</div> 				<div id="objEd-Interaction" class="objEd-Option"> 					<h2>Interação</h2> 				</div> 				<div id="objEd-Sound" class="objEd-Option"> 					<h2>Som</h2> 				</div> 				<div id="objEditor-close"></div>'
t("#objEditor").html(i),l()}function l(){function i(){for(t("#objEd-Color").append('<div id="objEd-Colors"></div>'),B=0;F.length>B;B++)t("#objEd-Colors").append('<div class="objEd-colorSelect" id="objEdCor-'+F[B]+'"></div>'),t("#objEdCor-"+F[B]).css("background-color","#"+F[B]),I[S].color=="#"+F[B]&&t("#objEdCor-"+F[B]).addClass("active")
t("#objEd-Colors div").click(function(i){var a=t(this).attr("id")
if(a=a.replace("objEdCor-","#"),console.log("color selected: "+a),a!=I[S].color){I[S].color=a,t("#objEditorCall").css("background-color",I[S].color),t(this).addClass("active").siblings().removeClass("active"),t("#objEd-Name").css("border-color",I[S].color)
var o=S+1
t("#objEd-Interacao tr:nth-child("+o+")").children("td:nth-child(2)").css("background-color",I[S].color)}i.stopPropagation()}),t("#objEd-Colors").slideDown(200)}function a(){t("#objEd-Size").append('<div id="objEd-Size-Slider"></div>'),t("#objEd-Size-Slider").slider({min:50,max:300,value:I[S].size,change:function(){I[S].size=t("#objEd-Size-Slider").slider("option","value")},slide:function(){I[S].size=t("#objEd-Size-Slider").slider("option","value")}}),t("#objEd-Size-Slider").slider("option","value",I[S].size),t("#objEd-Size-Slider").slideDown(200)}function o(){for(t("#objEd-Trajectory").append('<div id="objEd-Traj-Options"></div>'),B=0;8>B;B++){var i="traj_0"+(B+1)
t("#objEd-Traj-Options").append('<img src="img/editor/'+i+'.png" alt="trajetoria 06" width="50px" height="50px" />')}t("#objEd-Traj-Options img:nth-child("+I[S].path+")").addClass("active"),t("#objEd-Traj-Options img").click(function(i){var a=t(this).index()+1
a!=I[S].path&&(I[S].path=a,curTraj=I[S].path,t("#objEd-Traj-Options img.active").removeClass("active"),t("#objEd-Traj-Options img:nth-child("+curTraj+")").addClass("active")),i.stopPropagation()}),t("#objEd-Traj-Options").slideDown(200)}function e(){for(t("#objEd-Interaction").append('<div id="objEd-Int-Options"><table></table></div>'),B=0;I.length>B;B++){var i=B+1
t("#objEd-Int-Options table").append("<tr><td></td><td></td><td>ignorar</td><td>repelir</td><td>atrair</td></tr>"),t("#objEd-Int-Options tr:nth-child("+i+")").children("td:nth-child(1)").html("0"+i),t("#objEd-Int-Options tr:nth-child("+i+")").children("td:nth-child(2)").css("background-color",I[B].color)
var a=I[S].interaction[B]+2
t("#objEd-Int-Options tr:nth-child("+i+")").children("td:nth-child("+a+")").addClass("active")}t("#objEd-Int-Options").slideDown(200),t("#objEd-Int-Options td").click(function(i){var a=t(this).index()-1,o=t(this).parent().index(),n=I[S].interaction[o]
a!=n&&a>0&&(I[S].interaction[o]=a,o++,n+=2,a+=2,t("#objEd-Int-Options tr:nth-child("+o+")").children("td:nth-child("+n+")").removeClass("active"),t("#objEd-Int-Options tr:nth-child("+o+")").children("td:nth-child("+a+")").addClass("active")),i.stopPropagation()})}function s(){t("#objEd-Sound").append('<div id="objEd-Sound-Options"><ul></ul></div>')
for(var i=0;A.length>i;i++){var a="0"+(i+1)
t("#objEd-Sound-Options ul").append("<li>"+a+"</li>")}var o=I[S].sound
t("#objEd-Sound-Options li:nth-child("+o+")").addClass("active"),t("#objEd-Sound-Options").slideDown(200),t("#objEd-Sound-Options li").click(function(i){I[S].sound=t(this).index()+1,console.log("New creature sound: "+I[S].sound),t(this).addClass("active").siblings().removeClass("active"),i.stopPropagation()})}function r(){var i=["objEd-Colors","objEd-Size-Slider","objEd-Traj-Options","objEd-Int-Options","objEd-Sound-Options"]
for(B=0;i.length>B;B++){var a=t("#"+i[B])
a&&(a.parent().removeClass("active"),a.hide(200,function(){t(this).remove()}))}}(function(){for(t("#objEd-Index").html(""),B=0;I.length>B;B++){var i="0"+(B+1)
t("#objEd-Index").append('<li class="objEd-ObjIndex">'+i+"</li>")}if(O>I.length){var a='<li id="objEd-Index-Add"><img src="img/settings/set_plus.png" alt="create objet" width="8px" height="8px" /></li>'
t("#objEd-Index").append(a)}var o=S+1
t("#objEd-Index li:nth-child("+o+")").addClass("active"),t("#objEd-Name").val(I[S].name).css("border-color",I[S].color),t("#objEditorCall").css("background-color",I[S].color)})(),t("#objEd-Index li.objEd-ObjIndex").click(function(){S=t(this).index(),h()}),t("#objEd-Index-Add").click(function(){S=I.length,n(),h()}),t("#objEd-Name").keyup(function(){I[S].name=t(this).val()
var i=S+1
t("#objEd-Interacao tr:nth-child("+i+")").children("td:nth-child(3)").html(I[S].name)}),t("#objEd-Color").click(function(){t(this).addClass("active"),r(),i()}),t("#objEd-Size").click(function(){t(this).addClass("active"),r(),a()}),t("#objEd-Trajectory").click(function(){t(this).addClass("active"),r(),o()}),t("#objEd-Interaction").click(function(){t(this).addClass("active"),r(),e()}),t("#objEd-Sound").click(function(){t(this).addClass("active"),r(),s()})}function d(){var i='<div id="appMenuCall"><img src="img/settings/appmenucall.png" /></div>'
t("#mainWrapper").append(i),t("#appMenuCall").fadeIn(1e3),t("#appMenuCall").hover(function(){t("#objEditor").length>0?(t("#appMenuCall").animate({opacity:1},200),t("#objEditor").animate({opacity:.5},200),t("#objEditorCall").animate({opacity:.5},200)):t("#appMenu").length>0?t("#appMenu").animate({opacity:.5},200):t("#appMenuCall").css({"border-color":"#f8f8f8","background-color":"#f8f8f8"})},function(){t("#objEditor").length>0?(t("#objEditor").animate({opacity:1},200),t("#objEditorCall").animate({opacity:1},200),t("#appMenuCall").animate({opacity:.5},200)):t("#appMenu").length>0?(t("#appMenu").animate({opacity:1},200),t("#appMenuCall").css({opacity:"01","border-color":"#fff","background-color":"#fff"})):t("#appMenuCall").css({"border-color":"#fff","background-color":"#fff"})}),t("#appMenuCall").click(function(){t("#appMenu").length>0?(t("#appMenu").fadeOut(200,function(){t("#appMenu").remove()}),t("#objEditorCall").animate({opacity:1},200)):t("#objEditor").length>0?(t("#objEditor").fadeOut(200,function(){t("#objEditor").remove()}),c(),t("#appMenuCall").css({opacity:"01","border-color":"#fff","background-color":"#fff"}),t("#objEditorCall").animate({opacity:.5},200)):(t("#objEditorCall").animate({opacity:.5},200),c(),t("#appMenuCall").css({opacity:"01","border-color":"#fff","background-color":"#fff"}))})}function c(){var i='<article id="appMenu"><h1>Modo de Visualização</h1><ul> 					<li>Rastros Longos</li><li>Rastros Intermediários</li><li>Rastros Curtos</li><li>Círculos</li></ul><h1>Volume do Audio</h1><img id="soundVolumeOn" src="img/settings/volume_16_black.png" /><div id="soundVolume-slider"></div></article>'
t("#mainWrapper").append(i),t("#appMenu").fadeIn(200),t("#appMenu li:nth-child("+(m+1)+")").addClass("active"),t("#appMenu li").click(function(){t(this).index!=m&&(t("#appMenu li:nth-child("+(m+1)+")").removeClass("active"),m=t(this).index(),t("#appMenu li:nth-child("+(m+1)+")").addClass("active"))}),E&&(t("#soundVolumeOn").addClass("active"),t("#soundVolume-slider").addClass("active")),t("#soundVolumeOn").click(function(){if(E){soundManager.stopAll()
for(var i=0;I>i;i++)I[i].soundPlaying=[0,1],I[i].firstSound=!1
E=!1,t(this).removeClass("active"),t("#soundVolume-slider").removeClass("active")}else E=!0,t(this).addClass("active"),t("#soundVolume-slider").addClass("active")}),t("#soundVolume-slider").slider({min:0,max:100,value:C,change:function(){C=t("#soundVolume-slider").slider("option","value"),console.log("Sound volume is now: "+C)},slide:function(){C=t("#soundVolume-slider").slider("option","value")}})}function p(){var i="<div id='reloadCall'><img src='img/reload_white_28.png' width='28px' height='28px' /></div>"
t("#mainWrapper").append(i),t("#reloadCall").fadeIn(1e3).hover(function(){t("#reloadCall img").attr("src","img/reload_gray_28.png")},function(){t("#reloadCall img").attr("src","img/reload_white_28.png")}).click(function(){soundManager.stopAll()
for(var i=0;I>i;i++)I[i].soundPlaying=[0,1],I[i].firstSound=!1
a(),t("#objEditor").length>0&&h()})}function g(){for(var t=0;O>t;t++)for(var i=0;A.length>i;i++)for(var a=0;2>a;a++)for(var o=0;10>o;o++){var n=t+"_"+i+"_"+a+"_"+o,e="snd/"+o+A[i]
soundManager.createSound({id:n,url:e}),T++,738==T&&u()}}function u(){clearInterval(loadingAnimation),b.beginPath(),b.rect(0,0,k,x),b.fillStyle="rgba(240,240,240,0.8)",b.fill(),s(),d(),p(),v=!0,console.log("App is running.")}i(),t(window).resize(function(){i()})
var f=document.getElementById("mainCanvas")
if(f&&f.getContext("2d")){var b=f.getContext("2d")
if(null!=b){var v=!1,m=1,C=90,E=!0,M=.005,y=.15,X=4,Y=0,k=f.width,x=f.height,S=0,I=Array(),O=6,w=Array(),_=["Pedestre","Ciclista","Idoso","Criança","Adolescente","Skatista","Policial","Padeiro","Vendedor","Catador de Lixo","Bicicleta","Bueiro","Semáforo","Rua","Calçada","Loja","Casa","Casarão","Casinha","Prédio","Museu","Avenida","Poste","Banca de Jornal","Barraco","Hotel","Comércio","Vendinha","Feira","Faculdade","Porta","Homem","Mulher","Senhor","Bebê","Cachorro","Pato","Cavalo","Chuva","Sol","Vento","Árvore","Parque","Praça","Banco","Banco"],F=["000000","505050","FFFFFF","225C66","004966","3B0099","7F0C00","660C00","7F3430","662C00","CCBB42","49DB64","339944","00A898","787878","B4B4B4","8BB8C6","318399","005F99","6D00CC","66007F","CC2200","994734","664123","CC5C00","B2CC44","42CC5C","00D89A","DCDCDC","4AC2CC","40A8CC","0075CC","9500FF","B200CC","FF3600","CC6144","CC8544","FF7900","998A33","997F00","606624","00CC92","50CFD8","266466","0086FF","C480FF","F685FF","E600FF","FF7B52","FFA852","E5CA2E","E0BF00","CCAA00","96580C","1B4C20","007F55"]
o.prototype.sounds=function(){for(var t=!1,i=0;w.length>i;i++)if(w[i].type==this.index){t=!0
break}if(t){if(0==this.firstSound){var a=this.index
setTimeout(function(){I[a].soundPlaying[1]=0},3e3),this.firstSound=!0}for(var i=0;this.soundPlaying.length>i;i++)if(0==this.soundPlaying[i]){this.soundPlaying[i]=1
for(var o=0,n=0,e=k,s=x,r=0,h=0,l=0,d=0,c=0,j=0,p=0,g=0,u=0,f=0,b=0,v=0,m=0;w.length>m;m++)if(w[m].type==this.index){var E=Math.floor(w[m].x),M=Math.floor(w[m].y)
e>E&&(e=E),E>r&&(r=E),s>M&&(s=M),M>h&&(h=M)}l=Math.floor(e+(r-e)/2),d=Math.floor(s+(h-s)/2)
for(var m=0;w.length>m;m++)if(w[m].type==this.index){var E=Math.floor(w[m].x),M=Math.floor(w[m].y)
l>E?(p+=l-E,b++):E>l&&(g+=E-l,v++),d>M?u+=d-M:M>d&&(f+=M-d),j++,c+=M-s}o=l==e&&l==r?0:p>g?Math.floor(-100*(p/b/(l-e))):Math.floor(100*(g/v/(r-l))),n=1!=j?Math.floor(10*(c/j/(h-s))):Math.floor(10*(d/x))
var a=this.index,y=i,X=this.index+"_"+(this.sound-1)+"_"+i+"_"+n;(5!=this.sound&&1!=this.soundPlaying||6!=this.sound&&1!=this.soundPlaying)&&soundManager.play(X,{volume:C,pan:o,onfinish:function(){I[a].soundPlaying[y]=0}})}}},n(),e.prototype.move=function(){this.pX=this.x,this.pY=this.y,this.trajangle+=this.trajspeed
var t=I[this.type].size
switch(0!=this.lifeTime&&(this.trajpX=this.trajX,this.trajpY=this.trajY),I[this.type].path){case 1:this.trajX=this.initX-Math.cos(this.trajangle)*t,this.trajY=this.initY+Math.sin(this.trajangle)*t
break
case 2:this.trajX=this.initX-Math.sin(this.trajangle)*t,this.trajY=this.initY+Math.sin(this.trajangle)*t
break
case 3:switch(this.traj3angle+=this.trajspeed,this.traj3section){case 0:this.trajX=this.initX-t,this.trajY=this.initY-Math.sin(this.traj3angle)*t,Math.sin(this.traj3angle)>Math.sin(this.traj3angle+this.trajspeed)&&(this.traj3angle=0,this.traj3section++)
break
case 1:this.trajX=this.initX-Math.cos(this.traj3angle)*t,this.trajY=this.initY-t,Math.cos(this.traj3angle)<Math.cos(this.traj3angle+this.trajspeed)&&(this.traj3angle=0,this.traj3section++)
break
case 2:this.trajX=this.initX+t,this.trajY=this.initY-Math.cos(this.traj3angle)*t,Math.cos(this.traj3angle)<Math.cos(this.traj3angle+this.trajspeed)&&(this.traj3angle=0,this.traj3section++)
break
case 3:this.trajX=this.initX+Math.cos(this.traj3angle)*t,this.trajY=this.initY+t,Math.cos(this.traj3angle)<Math.cos(this.traj3angle+this.trajspeed)&&(this.traj3angle=0,this.traj3section++)
break
case 4:this.trajX=this.initX-t,this.trajY=this.initY+Math.cos(this.traj3angle)*t,Math.cos(this.traj3angle)<Math.cos(this.traj3angle+this.trajspeed)&&(this.traj3angle=0,this.traj3section=1)}break
case 4:this.trajX=this.initX+Math.sin(this.trajangle)*t,this.trajY=this.initY
break
case 5:this.trajX=this.initX,this.trajY=this.initY+Math.sin(this.trajangle)*t
break
case 6:switch(this.traj6angle+=this.trajspeed,this.traj6section){case 0:this.trajX=this.initX-t+Math.cos(this.traj6angle)*t,this.trajY=this.initY+Math.sin(this.traj6angle)*t,Math.cos(this.traj6angle)<Math.cos(this.traj6angle+this.trajspeed)&&this.traj6section++
break
case 1:this.trajX=this.initX-t+Math.cos(this.traj6angle)*t,this.trajY=this.initY+Math.sin(this.traj6angle)*t,Math.cos(this.traj6angle)>Math.cos(this.traj6angle+this.trajspeed)&&(this.traj6angle=0,this.traj6section++)
break
case 2:this.trajX=this.initX+t-Math.cos(this.traj6angle)*t,this.trajY=this.initY+Math.sin(this.traj6angle)*t,Math.cos(this.traj6angle)<Math.cos(this.traj6angle+this.trajspeed)&&this.traj6section++
break
case 3:this.trajX=this.initX+t-Math.cos(this.traj6angle)*t,this.trajY=this.initY+Math.sin(this.traj6angle)*t,Math.cos(this.traj6angle)>Math.cos(this.traj6angle+this.trajspeed)&&(this.traj6angle=0,this.traj6section=0)}break
case 7:this.trajX=this.initX+Math.sin(this.trajangle)*t,this.trajY=this.initY+Math.sin(this.trajangle)*t
break
case 8:switch(this.traj8angle+=this.trajspeed,this.traj8section){case 0:this.trajX=this.initX-Math.sin(this.traj8angle)*t,this.trajY=this.initY+t-Math.cos(this.traj8angle)*t,Math.sin(this.traj8angle)>Math.sin(this.traj8angle+this.trajspeed)&&(this.traj8angle=0,this.trajX=this.initX-t+Math.sin(this.traj8angle)*t,this.trajY=this.initY+Math.cos(this.traj8angle)*t,this.traj8section++)
break
case 1:this.trajX=this.initX-t+Math.sin(this.traj8angle)*t,this.trajY=this.initY+Math.cos(this.traj8angle)*t,Math.cos(this.traj8angle)<Math.cos(this.traj8angle+this.trajspeed)&&(this.traj8angle=0,this.trajX=this.initX-Math.cos(this.traj8angle)*t,this.trajY=this.initY-t+Math.sin(this.traj8angle)*t,this.traj8section++)
break
case 2:this.trajX=this.initX-Math.cos(this.traj8angle)*t,this.trajY=this.initY-t+Math.sin(this.traj8angle)*t,Math.cos(this.traj8angle)<Math.cos(this.traj8angle+this.trajspeed)&&(this.traj8angle=0,this.trajX=this.initX+t-Math.sin(this.traj8angle)*t,this.trajY=this.initY-Math.cos(this.traj8angle)*t,this.traj8section++)
break
case 3:this.trajX=this.initX+t-Math.sin(this.traj8angle)*t,this.trajY=this.initY-Math.cos(this.traj8angle)*t,Math.cos(this.traj8angle)<Math.cos(this.traj8angle+this.trajspeed)&&(this.traj8angle=0,this.trajX=this.initX+Math.cos(this.traj8angle)*t,this.trajY=this.initY+t-Math.sin(this.traj8angle)*t,this.traj8section++)
break
case 4:this.trajX=this.initX+Math.cos(this.traj8angle)*t,this.trajY=this.initY+t-Math.sin(this.traj8angle)*t,Math.sin(this.traj8angle)>Math.sin(this.traj8angle+this.trajspeed)&&(this.traj8angle=0,this.trajX=this.initX-Math.sin(this.traj8angle)*t,this.trajY=this.initY+t-Math.cos(this.traj8angle)*t,this.traj8section=0)}}0==this.lifeTime&&(this.trajpX=this.trajX,this.trajpY=this.trajY),this.x+=(this.trajX-this.trajpX)/2,this.y+=(this.trajY-this.trajpY)/2},e.prototype.moveInteraction=function(){if(this.lifeTime>0&&w[1])for(j=0;w.length>j;j++)if(j!=this.index){var t=(w[j].x-this.x)*M,i=(w[j].y-this.y)*M
switch(I[this.type].interaction[w[j].type]){case 2:1>t&&t>-1?t>.5?this.x--:-.5>t&&this.x++:this.x-=t,1>i&&i>-1?i>.5?this.y--:-.5>i&&this.y++:this.y-=i
break
case 3:1>t&&t>-1?t>.5?this.x++:-.5>t&&this.x--:this.x+=t,1>i&&i>-1?i>.5?this.y++:-.5>i&&this.y--:this.y+=i}}},e.prototype.display=function(){3>m?(b.beginPath(),b.moveTo(this.pX,this.pY),b.lineTo(this.x,this.y),b.lineWidth=1,b.strokeStyle=I[this.type].color,b.stroke()):(b.globalAlpha=.8,b.fillStyle=I[this.type].color,b.beginPath(),b.arc(this.x,this.y,6,0,2*Math.PI,!1),b.fill(),b.globalAlpha=1)},e.prototype.live=function(){this.move(),this.moveInteraction(),this.display(),this.lifeTime++},t("#mainCanvas").click(function(i){if(v){var a=i.pageX-t("#mainCanvas").offset().left,o=i.pageY-t("#mainCanvas").offset().top
w[w.length]=new e(a,o),console.log("Number of creatures is: "+w.length)}}),setInterval(function(){switch(x=f.height,k=f.width,m){case 0:break
case 1:Y==X?(b.rect(0,0,k,x),b.fillStyle="rgba(240,240,240,"+y+")",b.fill(),Y=0):Y++
break
case 2:case 3:b.rect(0,0,k,x),b.fillStyle="rgba(240,240,240,0.9)",b.fill()}if(w[0]){for(var t=0;w.length>t;t++)w[t].live()
if(E)for(var t=0;I.length>t;t++)I[t].sounds()}},33),soundManager.setup({url:"soundmanager/swf/",onready:function(){console.log("Soundmanager is set."),g()}})
for(var T=0,P=["reload_grey_28.png","reload_white_28.png","editor/int_atr.png","editor/int_nul.png","editor/int_rep.png","editor/traj_01.png","editor/traj_02.png","editor/traj_03.png","editor/traj_04.png","editor/traj_05.png","editor/traj_06.png","editor/traj_07.png","editor/traj_08.png","settings/appmenucall.png","settings/set_edit.png","settings/set_plus.png","settings/set_switch.png","settings/volume_16_black.png"],A=["mid","1mid","2mid","high","perc","bass"],B=0;P.length>B;B++)t("<img />").attr("src","img/"+P[B]),T++
loadingTime=0,loadingAnimation=setInterval(function(){b.beginPath(),b.rect(0,0,k,x),b.fillStyle="rgba(240,240,240,0.1)",b.fill(),b.lineWidth=4,b.strokeStyle="white",b.beginPath(),b.arc(k/2,x/2,12,loadingTime,loadingTime+1,!1),b.stroke(),loadingTime+=.25},33)}}})
